### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by mlema** [Morgan-and-Morgan/whistleblower-v2#22]
I have listed a couple of pages but please check the repo for commented code and remove it if we don't need it.

https://github.com/Morgan-and-Morgan/whistleblower-v2/blob/5e66736adb46359a325ca09cb22d134056f4c3aa/web/themes/custom/whistleblower/templates/layout/page.html.twig#L37

web/themes/custom/whistleblower/templates/content/node--attorney--attorney-teaser.html.twig
web/themes/custom/whistleblower/templates/content/node--attorney--full.html.twig
web/themes/custom/whistleblower/templates/content/node--blog-page--full.html.twig
web/themes/custom/whistleblower/templates/content/node--page--full.html.twig
web/themes/custom/whistleblower/templates/content/node--podcasts--full.html.twig
web/themes/custom/whistleblower/templates/content/node--videos--full.html.twig
web/themes/custom/whistleblower/templates/block/block--topposts.html.twig

**Comment by AndriiDreichan** [comment]
Fixed, please check @mlema
